# Generated by Django 3.2.9 on 2021-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0013_auto_20211213_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(max_length=255),
        ),
    ]
