# Generated by Django 3.2.9 on 2021-12-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0014_auto_20211213_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Theme',
        ),
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='primeflix_app.theme'),
            preserve_default=False,
        ),
    ]
