# Generated by Django 3.2.9 on 2021-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0018_auto_20211216_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default=True, max_length=200, unique=True),
        ),
    ]
