# Generated by Django 3.2.9 on 2021-12-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0020_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='date_created',
            new_name='date_update',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primeflix_app.customer'),
        ),
    ]
