# Generated by Django 3.2.9 on 2021-12-18 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0022_auto_20211218_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 16, 28, 1, 212570)),
        ),
    ]
